import { formatEquationSet } from '../physics/equationFormatter';
import { createPresets } from '../physics/presets';
import type { ProjectileParameters } from '../physics/projectile';
import type { QuizQuestion, QuizSkill } from './questionTypes';

type ChoiceQuestionType = 'choice' | 'equation' | 'sign' | 'origin' | 'swap';

const uniqueChoices = (answer: string, choices: string[]): string[] =>
  [answer, ...choices.filter((choice) => choice !== answer)].filter(
    (choice, index, all) => all.indexOf(choice) === index,
  );

const choiceQuestion = (
  id: string,
  type: ChoiceQuestionType,
  prompt: string,
  answer: string,
  choices: string[],
  explanation: string,
  skill: QuizSkill,
): QuizQuestion => ({
  id,
  type,
  prompt,
  choices: uniqueChoices(answer, choices),
  answer,
  explanation,
  skill,
});

export const buildQuestionBank = (params: ProjectileParameters): QuizQuestion[] => {
  const presets = createPresets(params);
  const equationPair = (presetIndex: number) => {
    const equations = formatEquationSet(params, presets[presetIndex]);
    return `${equations.axis1.simplifiedText}; ${equations.axis2.simplifiedText}`;
  };
  const equationChoices = (correctIndex: number, wrongIndices: number[]) =>
    uniqueChoices(
      equationPair(correctIndex),
      wrongIndices.map((index) => equationPair(index)),
    );

  return [
    choiceQuestion(
      'accel-positive-up',
      'choice',
      'A coordinate axis points vertically upward. What is the acceleration component along that axis?',
      '-g',
      ['+g', '0', 'v0'],
      'Gravity points downward, so it is negative along a positive-up axis.',
      'acceleration components',
    ),
    choiceQuestion(
      'accel-positive-down',
      'choice',
      'A coordinate axis points vertically downward. What is the acceleration component along that axis?',
      '+g',
      ['-g', '0', 'v0'],
      'Gravity points downward, so it is positive along a positive-down axis.',
      'acceleration components',
    ),
    choiceQuestion(
      'accel-horizontal-right',
      'choice',
      'A coordinate axis points horizontally right. What is the acceleration component along that axis?',
      '0',
      ['+g', '-g', 'v0'],
      'Gravity is vertical, so it has no component along a horizontal axis.',
      'acceleration components',
    ),
    choiceQuestion(
      'accel-term-up',
      'sign',
      'If the positive vertical coordinate points upward, what sign should the gravity term have?',
      'negative',
      ['positive', 'zero'],
      'The projectile accelerates opposite a positive-up direction.',
      'axis orientation',
    ),
    choiceQuestion(
      'accel-term-down',
      'sign',
      'If the positive vertical coordinate points downward, what sign should the gravity term have?',
      'positive',
      ['negative', 'zero'],
      'The projectile accelerates with a positive-down direction.',
      'axis orientation',
    ),
    choiceQuestion(
      'accel-flip-vertical',
      'sign',
      'You flip only the vertical axis. What happens to the sign of the acceleration term in that coordinate?',
      'it changes sign',
      ['it stays the same', 'it becomes zero', 'it becomes v0'],
      'Flipping an axis multiplies every component along that axis by -1.',
      'axis orientation',
    ),
    choiceQuestion(
      'accel-flip-horizontal',
      'sign',
      'You flip only the horizontal axis. What happens to the vertical acceleration term?',
      'it stays the same',
      ['it changes sign', 'it becomes zero', 'it becomes v0'],
      'Flipping the horizontal axis does not change components along the vertical axis.',
      'axis orientation',
    ),
    choiceQuestion(
      'velocity-right-axis',
      'choice',
      'The launch velocity points right. What is its component along an axis that points right?',
      '+v0',
      ['-v0', '0', '+g'],
      'The velocity points in the same direction as a positive-right axis.',
      'velocity components',
    ),
    choiceQuestion(
      'velocity-left-axis',
      'choice',
      'The launch velocity points right. What is its component along an axis that points left?',
      '-v0',
      ['+v0', '0', '-g'],
      'The velocity points opposite a positive-left axis.',
      'velocity components',
    ),
    choiceQuestion(
      'velocity-up-axis',
      'choice',
      'The launch velocity points right. What is its component along a vertical-up axis?',
      '0',
      ['+v0', '-v0', '-g'],
      'The launch is horizontal, so it has no vertical component.',
      'velocity components',
    ),
    choiceQuestion(
      'velocity-down-axis',
      'choice',
      'The launch velocity points right. What is its component along a vertical-down axis?',
      '0',
      ['+v0', '-v0', '+g'],
      'The launch is horizontal, so flipping the vertical axis still gives zero vertical velocity.',
      'velocity components',
    ),
    choiceQuestion(
      'velocity-flip-horizontal',
      'sign',
      'You flip only the horizontal axis from right to left. What happens to the launch velocity component?',
      'it changes from +v0 to -v0',
      ['it stays +v0', 'it becomes +g', 'it becomes -g'],
      'The physical velocity is still rightward, but the positive coordinate direction is now leftward.',
      'velocity components',
    ),
    choiceQuestion(
      'velocity-origin-move',
      'choice',
      'You move the origin but do not rotate or flip the axes. What happens to the velocity components?',
      'they do not change',
      ['they both become zero', 'they change sign', 'they become position components'],
      'Translating the origin changes position coordinates, not velocity vectors.',
      'velocity components',
    ),
    choiceQuestion(
      'origin-cliff-top-default',
      'origin',
      'Origin at the cliff top, x right, y up. What are the initial coordinates?',
      '(0, 0)',
      ['(0, H)', '(H, 0)', '(d1, h)'],
      'The launch point is exactly at the origin.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-ground-up',
      'origin',
      'Origin on the ground below the cliff, y positive upward. What is the initial y coordinate?',
      'H',
      ['0', '-H', 'h'],
      'The launch point is H meters above the ground origin.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-ground-down',
      'origin',
      'Origin on the ground below the cliff, y positive downward. What is the initial y coordinate?',
      '-H',
      ['H', '0', '-h'],
      'The launch point is above the origin, which is negative for a downward-positive axis.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-wall-x',
      'origin',
      'Origin at the wall top, x positive right. What is the initial x coordinate of the projectile?',
      '-d1',
      ['d1', '0', 'd2'],
      'The launch point is d1 meters left of the wall origin.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-wall-y',
      'origin',
      'Origin at the wall top, y positive upward. What is the initial y coordinate?',
      'H - h',
      ['h - H', 'H', 'h'],
      'The launch point is H above ground while the wall top is h above ground.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-landing-x-right',
      'origin',
      'Origin near the landing point at horizontal position d1 + d2, with x positive right. What is the initial x coordinate?',
      '-d1 - d2',
      ['d1 + d2', '0', '-d1'],
      'The launch point is left of the landing origin by d1 + d2.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-landing-x-left',
      'origin',
      'Origin near the landing point at horizontal position d1 + d2, with x positive left. What is the initial x coordinate?',
      'd1 + d2',
      ['-d1 - d2', '0', 'd2'],
      'Leftward is positive, and the launch point is left of the landing origin.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-move-effect',
      'choice',
      'Moving the origin affects which part of the component equations?',
      'initial position terms only',
      ['velocity terms only', 'acceleration terms only', 'all signs automatically'],
      'A translation changes where positions are measured from, but not velocity or acceleration.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-above-launch',
      'origin',
      'If the origin is moved above the launch point and y is positive upward, the initial y coordinate is...',
      'negative',
      ['positive', 'zero', 'always H'],
      'The launch point is below that origin, so its y coordinate is negative.',
      'origin placement',
    ),
    choiceQuestion(
      'origin-below-launch',
      'origin',
      'If the origin is moved below the launch point and y is positive upward, the initial y coordinate is...',
      'positive',
      ['negative', 'zero', 'always -H'],
      'The launch point is above that origin, so its y coordinate is positive.',
      'origin placement',
    ),
    choiceQuestion(
      'equation-default',
      'equation',
      'Origin at cliff top, x right, y up. Which equation pair is correct?',
      equationPair(0),
      equationChoices(0, [3, 4, 1]),
      'The origin is the launch point, x follows the launch velocity, and y points opposite gravity.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-left-up',
      'equation',
      'Origin at cliff top, x left, y up. Which equation pair is correct?',
      equationPair(1),
      equationChoices(1, [0, 2, 4]),
      'The horizontal coordinate is flipped, so the velocity term along x is negative.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-left-down',
      'equation',
      'Origin at cliff top, x left, y down. Which equation pair is correct?',
      equationPair(2),
      equationChoices(2, [1, 3, 7]),
      'Both axes are flipped relative to the default directions.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-right-down',
      'equation',
      'Origin at cliff top, x right, y down. Which equation pair is correct?',
      equationPair(3),
      equationChoices(3, [0, 2, 5]),
      'The downward y axis points with gravity, so the y acceleration term is positive.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-ground-up',
      'equation',
      'Origin on the ground below the cliff, x right, y up. Which equation pair is correct?',
      equationPair(4),
      equationChoices(4, [0, 5, 8]),
      'Moving the origin to the ground adds the initial height H to the vertical equation.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-ground-down',
      'equation',
      'Origin on the ground below the cliff, x right, y down. Which equation pair is correct?',
      equationPair(5),
      equationChoices(5, [3, 4, 6]),
      'The launch point starts at -H because it is above a downward-positive origin.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-ground-left-down',
      'equation',
      'Origin on the ground below the cliff, x left, y down. Which equation pair is correct?',
      equationPair(6),
      equationChoices(6, [5, 7, 2]),
      'Both velocity and vertical position signs reflect the flipped axes.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-ground-left-up',
      'equation',
      'Origin on the ground below the cliff, x left, y up. Which equation pair is correct?',
      equationPair(7),
      equationChoices(7, [4, 6, 1]),
      'The x velocity is negative because positive x points left, while y starts at H.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-wall-top',
      'equation',
      'Origin at the wall top, x right, y up. Which equation pair is correct?',
      equationPair(8),
      equationChoices(8, [4, 0, 10]),
      'The launch point starts left of and above the wall-top origin.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-swapped',
      'equation',
      'Origin on the ground below the cliff, x vertical up, y horizontal right. Which equation pair is correct?',
      equationPair(9),
      equationChoices(9, [4, 0, 3]),
      'The vertical coordinate is named x, so the gravity term belongs to x(t).',
      'swapped axes',
    ),
    choiceQuestion(
      'equation-landing-ab',
      'equation',
      'Origin near the landing point, a right, b up. Which equation pair is correct?',
      equationPair(10),
      equationChoices(10, [11, 4, 8]),
      'The labels changed to a and b, and the launch point begins left of the origin.',
      'equation construction',
    ),
    choiceQuestion(
      'equation-landing-flipped-ab',
      'equation',
      'Origin near the landing point, a left, b down. Which equation pair is correct?',
      equationPair(11),
      equationChoices(11, [10, 6, 3]),
      'Both custom axes are flipped, so signs change along a and b.',
      'equation construction',
    ),
    choiceQuestion(
      'swap-gravity-coordinate',
      'swap',
      'If x points vertically upward and y points horizontally right, which equation contains the gravity term?',
      'x(t)',
      ['y(t)', 'both equations', 'neither equation'],
      'The gravity term follows the vertical coordinate, even when that coordinate is named x.',
      'swapped axes',
    ),
    choiceQuestion(
      'swap-velocity-coordinate',
      'swap',
      'If x points vertically upward and y points horizontally right, which equation contains the launch velocity term?',
      'y(t)',
      ['x(t)', 'both equations', 'neither equation'],
      'The launch velocity is horizontal, and the horizontal coordinate is named y.',
      'swapped axes',
    ),
    choiceQuestion(
      'swap-x-down',
      'swap',
      'If x points vertically downward and y points horizontally right, what sign is the gravity term in x(t)?',
      'positive',
      ['negative', 'zero', 'it belongs in y(t)'],
      'A downward-positive x axis points with gravity.',
      'swapped axes',
    ),
    choiceQuestion(
      'swap-y-left',
      'swap',
      'If x points vertically upward and y points horizontally left, what is the launch velocity component in y?',
      '-v0',
      ['+v0', '0', '-g'],
      'The launch is rightward, which is opposite a positive-left y axis.',
      'swapped axes',
    ),
    choiceQuestion(
      'swap-labels-only',
      'swap',
      'Relabeling axes from x,y to a,b without moving or flipping them changes what?',
      'the symbols in the equations',
      ['the physical path', 'the direction of gravity', 'the launch speed'],
      'Relabeling changes names, not the underlying physical vectors.',
      'swapped axes',
    ),
    choiceQuestion(
      'swap-which-name',
      'swap',
      'A coordinate named r points vertically upward and s points horizontally right. Which coordinate gets the -1/2 g t^2 term?',
      'r(t)',
      ['s(t)', 'both', 'neither'],
      'The vertical-up coordinate is r, so gravity appears in r(t).',
      'swapped axes',
    ),
    choiceQuestion(
      'rotation-velocity-axis1',
      'choice',
      'Axis 1 is rotated by theta from the positive world-x direction. What is the launch velocity component along axis 1?',
      'v0 cos(theta)',
      ['v0 sin(theta)', '-g sin(theta)', '0'],
      'The rightward launch velocity projects onto the rotated axis with a cosine factor.',
      'velocity components',
    ),
    choiceQuestion(
      'rotation-accel-axis1',
      'choice',
      'Axis 1 is rotated by theta from the positive world-x direction. What is the acceleration component along axis 1?',
      '-g sin(theta)',
      ['g cos(theta)', 'v0 cos(theta)', '0'],
      'Gravity points downward, and the vertical projection of axis 1 is sin(theta).',
      'acceleration components',
    ),
    choiceQuestion(
      'rotation-velocity-axis2',
      'choice',
      'With a counterclockwise orthogonal axis 2, what is the launch velocity component along axis 2?',
      '-v0 sin(theta)',
      ['v0 cos(theta)', 'v0 sin(theta)', '-g cos(theta)'],
      'Axis 2 has horizontal projection -sin(theta), so a rightward velocity projects as -v0 sin(theta).',
      'velocity components',
    ),
    choiceQuestion(
      'rotation-accel-axis2',
      'choice',
      'With a counterclockwise orthogonal axis 2, what is the acceleration component along axis 2?',
      '-g cos(theta)',
      ['-g sin(theta)', 'v0 sin(theta)', '0'],
      'Axis 2 has vertical projection cos(theta), and gravity points downward.',
      'acceleration components',
    ),
    choiceQuestion(
      'rotation-term-distribution',
      'choice',
      'When the axes are rotated away from horizontal and vertical, where can the gravity term appear?',
      'in both coordinate equations',
      ['only in y(t)', 'only in x(t)', 'in neither equation'],
      'A rotated pair of axes can both have vertical projection, so gravity can project onto both.',
      'equation construction',
    ),
    {
      id: 'components-default',
      type: 'components',
      prompt: 'Default origin at the cliff top, x right, y up. Fill the two simplified equations.',
      blanks: ['x(t)', 'y(t)'],
      choices: ['v0 t', '-v0 t', '1/2 g t^2', '-1/2 g t^2', 'H - 1/2 g t^2', '0'],
      answer: ['v0 t', '-1/2 g t^2'],
      explanation: 'The projectile starts at the origin, moves right with v0, and accelerates downward.',
      skill: 'equation construction',
    },
    {
      id: 'components-ground-up',
      type: 'components',
      prompt: 'Ground origin, x right, y up. Fill the two simplified equations.',
      blanks: ['x(t)', 'y(t)'],
      choices: ['v0 t', '-v0 t', 'H - 1/2 g t^2', '-H + 1/2 g t^2', '1/2 g t^2', '0'],
      answer: ['v0 t', 'H - 1/2 g t^2'],
      explanation: 'The origin moved downward, so the initial vertical coordinate is H.',
      skill: 'origin placement',
    },
    {
      id: 'short-origin',
      type: 'short',
      prompt: 'In one or two sentences, explain why moving the origin changes position terms but not velocity or acceleration terms.',
      keyIdeas: ['origin', 'position', 'velocity', 'acceleration'],
      sample:
        'Moving the origin changes what point positions are measured from. Velocity and acceleration are vector directions and rates, so translating the origin does not change their components.',
      explanation:
        'A translation changes relative position vectors, but it does not change the physical velocity or acceleration vectors.',
      skill: 'origin placement',
    },
    {
      id: 'short-rotation',
      type: 'short',
      prompt: 'In one or two sentences, explain why a rotated coordinate system can put gravity terms in both equations.',
      keyIdeas: ['rotated', 'gravity', 'component', 'axis'],
      sample:
        'When the axes are rotated, each axis can have some vertical direction in it. Gravity projects onto any axis with a vertical component.',
      explanation: 'A rotated axis can share part of the downward direction, so gravity is projected by dot product.',
      skill: 'equation construction',
    },
  ];
};
