import type { ProjectileParameters } from './projectile';
import type { CoordinateSystem } from './coordinateSystem';
import { vector } from './vectors';

export type CoordinatePreset = CoordinateSystem & {
  id: string;
  originKey: 'cliffTop' | 'groundBelowCliff' | 'wallTop' | 'landingPoint';
};

export const createPresets = (params: ProjectileParameters): CoordinatePreset[] => [
  {
    id: '1',
    name: 'Cliff top, x right, y up',
    description: 'Origin at launch point; horizontal positive right; vertical positive up.',
    originKey: 'cliffTop',
    originWorld: vector(0, params.H),
    axis1: vector(1, 0),
    axis2: vector(0, 1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '2',
    name: 'Cliff top, x left, y up',
    description: 'Launch point origin with horizontal axis flipped against the velocity.',
    originKey: 'cliffTop',
    originWorld: vector(0, params.H),
    axis1: vector(-1, 0),
    axis2: vector(0, 1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '3',
    name: 'Cliff top, x left, y down',
    description: 'Both physical directions are flipped from the default labels.',
    originKey: 'cliffTop',
    originWorld: vector(0, params.H),
    axis1: vector(-1, 0),
    axis2: vector(0, -1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '4',
    name: 'Cliff top, x right, y down',
    description: 'Horizontal matches launch velocity; vertical points with gravity.',
    originKey: 'cliffTop',
    originWorld: vector(0, params.H),
    axis1: vector(1, 0),
    axis2: vector(0, -1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '5',
    name: 'Ground origin, x right, y up',
    description: 'Origin moved to the ground below launch while directions stay conventional.',
    originKey: 'groundBelowCliff',
    originWorld: vector(0, 0),
    axis1: vector(1, 0),
    axis2: vector(0, 1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '6',
    name: 'Ground origin, x right, y down',
    description: 'Origin at ground; vertical coordinate increases downward.',
    originKey: 'groundBelowCliff',
    originWorld: vector(0, 0),
    axis1: vector(1, 0),
    axis2: vector(0, -1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '7',
    name: 'Ground origin, x left, y down',
    description: 'Origin at ground; both axes are opposite of the usual directions.',
    originKey: 'groundBelowCliff',
    originWorld: vector(0, 0),
    axis1: vector(-1, 0),
    axis2: vector(0, -1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '8',
    name: 'Ground origin, x left, y up',
    description: 'Origin at ground; horizontal coordinate is positive left.',
    originKey: 'groundBelowCliff',
    originWorld: vector(0, 0),
    axis1: vector(-1, 0),
    axis2: vector(0, 1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '9',
    name: 'Wall top origin, x right, y up',
    description: 'Origin near the wall top, so the launch point starts left and above that origin.',
    originKey: 'wallTop',
    originWorld: vector(params.d1, params.h),
    axis1: vector(1, 0),
    axis2: vector(0, 1),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '10',
    name: 'Swapped variables: x vertical, y horizontal',
    description: 'The coordinate named x is vertical upward; the coordinate named y is horizontal right.',
    originKey: 'groundBelowCliff',
    originWorld: vector(0, 0),
    axis1: vector(0, 1),
    axis2: vector(1, 0),
    label1: 'x',
    label2: 'y',
  },
  {
    id: '11',
    name: 'Landing origin, a right, b up',
    description: 'Custom labels with the origin near the landing region.',
    originKey: 'landingPoint',
    originWorld: vector(params.d1 + params.d2, 0),
    axis1: vector(1, 0),
    axis2: vector(0, 1),
    label1: 'a',
    label2: 'b',
  },
  {
    id: '12',
    name: 'Landing origin, a left, b down',
    description: 'Custom labels with both directions flipped near the landing region.',
    originKey: 'landingPoint',
    originWorld: vector(params.d1 + params.d2, 0),
    axis1: vector(-1, 0),
    axis2: vector(0, -1),
    label1: 'a',
    label2: 'b',
  },
];
